# labeled_anomalies.yaml
# 基于ARMD模型和标注异常数据的完整配置

# 继承基础模型参数
_base_: etth1.yaml

# 数据配置增强
dataset:
  name: ETTh1_Anomaly
  data_path: ./Data/datasets/ETTh1.csv
  anomaly_labels_path: ./Data/datasets/labeled_anomalies.csv
  feature_columns: ["HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL", "OT"]
  anomaly_label_column: "anomaly_flag"  # 新增异常标记列

# 模型架构调整
model:
  target: Models.autoregressive_diffusion.armd.ARMD
  params:
    seq_length: 96
    feature_size: 8  # 原始7特征 + 1异常标记
    anomaly_aware: True
    attention_mask: True  # 启用异常区域注意力掩码

# 训练流程优化
trainer:
  batch_size: 64
  max_epochs: 1000
  gradient_accumulation_steps: 2
  anomaly_weight: 0.7  # 异常区域损失权重

  checkpoint:
    dir: ./anomaly_checkpoints
    save_every: 100

# 异常处理模块
anomaly_processor:
  preprocess:
    - method: normalize
      range: [-1, 1]
    - method: label_injection  # 注入标注异常信息
      source: labeled_anomalies.csv
      field_mapping:
        chan_id: channel
        spacecraft: source_system
        anomaly_sequences: anomaly_windows

# 评估配置
evaluator:
  metrics:
    - name: point_anomaly_f1
      type: pointwise
      overlap: 0.5
    - name: contextual_anomaly_auc
      type: segment
      min_overlap: 0.7
  report_format: detailed_markdown
